package com.ignisign.ignisign.public

enum class IgnisignSignerClaimRef {
    EID_POSSESSION_AES,
    EID_POSSESSION_QES,
    PHONE_NUMBER_POSSESSION,
    PRIVATE_KEY_POSSESSION,
    DAPP_WALLET_POSSESSION,
    APP_SIGNER_SECRET_POSSESSION,
    TOTP_POSSESSION,
    EMAIL_POSSESSION,
    ID_DOC_POSSESSION_QES,
    ID_DOC_POSSESSION_AES,
    SOCIAL_SECURITY_NUMBER_POSSESSION,
    RA_PROCESS_VALIDATED_AES,
    RA_PROCESS_VALIDATED_QES,
    BANK_ACCOUNT_POSSESSION,
    NATURAL_PERSON_NAME,
    LEGAL_PERSON_NAME,
    PASS_KEY_POSSESSION,
    NATIONALITY,
    BIRTH_INFO
}

enum class IgnisignSignerClaimStatus {
    DECLARED,
    VERIFIED,
    REJECTED,
    DEPRECATED
}